### ISSUE TITLE
Preveri zakaj nekateri uporabniki ne dobijo "Lost password" emaila

### ISSUE THREAD

**Issue by HriBB** [aokranj/website#13]

**Comment by bostjan** [comment]
Dej mi en primer takega uporabnika, da preverim po logih (+ približen cajt) pa mi issue reassignej.

b.

**Comment by HriBB** [comment]
Matej Arh in Marko Šink pravita da nista dobila.
Čist možno je da je šlo v spam in nista pogrunatala.
Možno je tudi da uporabljata kak drug email, čeprav v tem primeru bi wordpress zajamral, da mail ne obstaj.

**Comment by bostjan** [comment]
Ne, na yahooju je težava, vsaj Svoljšak vidim da je na tem naslovu in vidim da rejecta maile s tega serverja, dokaj bedno.

Bom probal uredit, ali pa bom maile zrutal preko drugih IPjev.

**Comment by bostjan** [comment]
Poslan request na hotmail, upam da removajo zadevo ASAP.

Tole je pomoje posledica spamanja čez prejšen website, čez kontakt form.

**Comment by bostjan** [comment]
A preveriš emaila od Arha in Šinka, če sta tudi na hotmailu?

**Comment by bostjan** [comment]
Od microsofta:


We have completed reviewing the IP(s) you submitted. The following table contains the results of our investigation.


Conditionally mitigated
5.9.186.178
Our investigation has determined that the above IP(s) qualify for conditional mitigation. These IP(s) have been unblocked, but may be subject to low daily email limits until they have established a good reputation.

Please note that mitigating this issue does not guarantee that your email will be delivered to a user’s inbox.

Ongoing complaints from users will result in removal of the mitigation.

Mitigation may take 24 - 48 hours to replicate completely throughout our system.

If you feel your issue is not yet resolved, please reply to this email and one of our support team members will contact you for further investigation.

**Comment by HriBB** [comment]
Arh ma majtearh@hotmail.com, Marko ma marko.sink@hotmail.com.

Šink mi je včeraj reku da mu zdej pa dela, tako da zgleda je problem rešen. Ja?

**Comment by bostjan** [comment]
Yup, se vidi v postmaster toolu od hotmaila. Raylog mislim da je bil tisto spamanje preko kontaktnega obrazca in preko foruma.
